language: scala
sudo: false
jdk:
- oraclejdk8
scala:
- 2.11.8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_script:
- mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin
- curl -L "https://bintray.com/dit4c/build-utils/download_file?file_path=gnupg-2.1.16%2Fgpg2" > $HOME/bin/gpg2 && chmod +x $HOME/bin/gpg2
- echo $PATH
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean update
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M coverage test coverageReport
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- sbt coverageAggregate
- sbt coveralls
notifications:
  slack:
    rooms:
      secure: CvQrl/OQx9BzIG+G8mrUYnCtYmvjoElXFDxb3q7KnA65H4plp3sKORHk74Gy3vwOeSdxRXgIutoNnrZjn0x2foP+gnLQ5IMu2I69tphBBAb/TLRzIu57H4Vi0EB3oWTTlYLfjKnyhzUvpj1+AG7exzWY3ASom0j+BG9z8Tl/ywQ=
    on_success: change
    on_failure: change
