language: scala
sudo: true
jdk:
  - oraclejdk8
scala:
  - 2.11.6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/nginx
before_install:
  - |
    BASE=$HOME && \
    test -f $BASE/nginx/sbin/nginx || \
    (curl -L -s https://github.com/nginx/nginx/archive/release-1.9.5.tar.gz | tar xz -C $BASE && \
    cd $BASE/nginx-release-1.9.5 && \
    auto/configure \
        --prefix=$BASE/nginx \
        --conf-path=$BASE/etc/nginx/nginx.conf \
        --http-log-path=/dev/stdout \
        --error-log-path=/dev/stderr \
        --with-http_auth_request_module \
        --with-http_v2_module \
        --with-http_ssl_module \
        --without-http_ssi_module \
        --without-http_userid_module \
        --without-http_access_module \
        --without-http_auth_basic_module \
        --without-http_autoindex_module \
        --without-http_geo_module \
        --without-http_split_clients_module \
        --without-http_fastcgi_module \
        --without-http_uwsgi_module \
        --without-http_scgi_module \
        --without-http_memcached_module \
        --without-http_limit_conn_module \
        --without-http_limit_req_module \
        --without-http_empty_gif_module \
        --without-http_browser_module && \
    make && \
    make install && \
    cd - && \
    rm -rf $BASE/nginx-release-1.9.5) && \
    ls -laR $BASE/nginx && \
    export PATH=$BASE/nginx/sbin:$PATH
  - |
    BASE=$HOME && \
    test -f $BASE/rkt/rkt || \
    curl -L https://github.com/coreos/rkt/releases/download/v1.6.0/rkt-v1.6.0.tar.gz | tar xzv -C $BASE && \
    mv $BASE/rkt-v1.6.0 $BASE/rkt && \
    export PATH=$BASE/rkt:$PATH
before_script:
  - echo $PATH
  - couchdb -V
  - nginx -V
  - rkt version
script:
  # Test script
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test && sbt coverageAggregate
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - sbt coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f8d2a73ac3672d8e7a8e
    on_success: change
    on_failure: always
    on_start: false
