language: scala
sudo: required
jdk:
- oraclejdk8
scala:
- 2.11.8
addons:
  apt:
    packages:
    - gnupg2
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_script:
- echo $PATH
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean update
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M coverage test coverageReport
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- sbt coverageAggregate
- sbt coveralls
notifications:
  slack:
    rooms:
      secure: Zrs/pBEIdYh3qkqRH9Ebr5qvwpGHkXBq09Gevf4ZVUXd1UsJcF+RMvwTLOsMIbQfW2UjhpfhzOJg4HcFLzOw+FHFh0Rd4l34VLGRl6jeiPs4pumQ8LoK80zMA80Vbg98eI+tRjUy0KJhMk2MUN50WhSPCVq+HDcnauPEbgG+wxU=
    on_success: change
    on_failure: change
