language: scala
sudo: true
jdk:
  - oraclejdk8
scala:
  - 2.11.6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_script:
  - echo $PATH
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean update
script:
  # Test script
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M coverage test && sbt coverageAggregate
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - sbt coveralls
