language: scala
sudo: false
jdk:
  - oraclejdk8
scala:
  - 2.11.6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_script:
  - couchdb -V
  - nginx -V
script:
  # Test script
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f8d2a73ac3672d8e7a8e
    on_success: change
    on_failure: always
    on_start: false
addons:
  apt:
    packages:
      - nginx
